import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, relative } from 'node:path';

// Slice 11: generate a per-Space Dockerfile by detecting the project's
// existing one and appending the Sandcastle agent layer. Output goes
// into `spaces.dockerfile_content`, edited by a human via the Edit
// Space UI (HITL — multi-stage caveats, BuildKit usage, language
// quirks all require judgment).
//
// Pure function: takes a host path to the cloned repo, returns the
// merged content + diagnostics. No DB / network side effects.

export type GenerateResult = {
  content: string;
  // Relative path of the source Dockerfile we detected, or null if we
  // fell back to the node:22 skeleton.
  detectedFrom: string | null;
  // Non-fatal warnings the human reviewer needs to know about before
  // saving. The UI surfaces these above the editor.
  warnings: string[];
};

// Scan order matters — `.dev` first because dev-flavored Dockerfiles
// usually have looser permissions / shells available which suit the
// agent runtime; production Dockerfiles tend to be hardened (distroless,
// minimal package sets) and need more edits.
const CANDIDATE_PATHS = [
  'Dockerfile.dev',
  'Dockerfile',
  'docker/Dockerfile',
  '.docker/Dockerfile',
];

// The agent layer is appended after the project's content. Final stage
// owns the WORKDIR + ENTRYPOINT. The user can edit this in the UI
// before saving if their image needs a different base package set
// (e.g. apk for Alpine).
const AGENT_LAYER = `
# ─── Sandcastle agent layer (generated by jir; edit before saving) ───
# Installs the Claude Code CLI + minimum tools the agent needs. If the
# base image already has these (most do — node/python/ruby images all
# include git + curl), the apt-get install is a no-op. Adjust for
# alpine / distroless bases.
USER root

# Pin a sane PATH so our exec'd commands (git, sh, etc.) resolve
# regardless of what the project's Dockerfile set. Many legacy
# images override PATH to point at app-specific bins; without this
# reset, sh would fail to find /usr/bin/git inside the container
# and Sandcastle's first sandbox probe (git rev-parse) exits 127.
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Node 22 via NodeSource: required by @openai/codex (modern Node),
# and works on Ubuntu/Debian regardless of base age (Bookworm,
# Bullseye, Bionic). We deliberately don't use the distro's
# 'nodejs' apt package — on older bases (Ubuntu 18.04 etc.) it's
# ancient (v8/v10) and the agent CLIs won't run.
RUN apt-get update && apt-get install -y --no-install-recommends \\
      git curl jq ca-certificates gnupg \\
 && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \\
 && apt-get install -y --no-install-recommends nodejs \\
 && rm -rf /var/lib/apt/lists/*

# Both agent CLIs are installed so the per-Space image is
# provider-agnostic — Sandcastle picks claude or codex at runtime
# based on the Space's saved agent account. Image size cost is ~few
# tens of MB, paid once per Space (then cached).
# npm install -g puts the bin symlink in /usr/local/bin, which is on
# the PATH set above. The install.sh script writes to ~/.local/bin,
# which is NOT on that PATH and also fails silently in non-interactive
# Docker builds — so we use npm here instead.
RUN npm install -g @anthropic-ai/claude-code
RUN npm install -g @openai/codex

# The agent user gets the next free uid. We deliberately don't pin
# uid 1000 — most language base images (node, lighttpd, etc.) already
# own it, and silently masking the collision with '|| true' produces
# a broken image where 'USER agent' references a user that doesn't
# exist (docker run fails with "no matching entries in passwd file").
# Letting useradd pick a free uid + no '|| true' means collisions
# fail loud at build time, where we can fix them.
RUN id -u agent >/dev/null 2>&1 || useradd -m -s /bin/bash agent
USER agent
WORKDIR /home/agent

# ENTRYPOINT keeps the container alive while Sandcastle docker-execs
# the agent process into it. CMD is reset to [] so any CMD inherited
# from the project's Dockerfile doesn't get concatenated onto sleep
# as args (Docker combines ENTRYPOINT + CMD into one argv — without
# the reset, 'sleep infinity /path/to/project-cmd.sh' is what runs,
# which sleep rejects and exits 1).
ENTRYPOINT ["sleep", "infinity"]
CMD []
`.trimStart();

const NODE_SKELETON = `
FROM node:22-bookworm-slim

# No Dockerfile detected in the repo — using a node:22 base as a
# generic fallback. If your project needs a different runtime (PHP,
# Python, Go, etc.) edit this to match before saving.
`.trimStart();

export async function generate(args: { repoPath: string }): Promise<GenerateResult> {
  const { repoPath } = args;
  const warnings: string[] = [];

  // 1-2. Scan candidate paths.
  let detected: { path: string; content: string } | null = null;
  for (const rel of CANDIDATE_PATHS) {
    const abs = join(repoPath, rel);
    if (existsSync(abs)) {
      const content = await readFile(abs, 'utf8');
      detected = { path: relative(repoPath, abs), content };
      break;
    }
  }

  // 3. Fallback skeleton.
  let base: string;
  let detectedFrom: string | null;
  if (detected) {
    base = detected.content;
    detectedFrom = detected.path;
  } else {
    base = NODE_SKELETON;
    detectedFrom = null;
    warnings.push(
      'No Dockerfile found in repo (scanned: ' +
        CANDIDATE_PATHS.join(', ') +
        '). Using a node:22-bookworm-slim base — edit before saving if your project needs a different runtime.',
    );
  }

  // 4. Multi-stage detection: count `FROM ... AS <name>` blocks.
  const stages = parseStages(base);
  if (stages.length > 1) {
    warnings.push(
      `Multi-stage Dockerfile detected (${stages.length} stages: ${stages
        .map((s) => s.name || '(unnamed)')
        .join(', ')}). The Sandcastle agent layer attaches to the LAST stage only. If your project's final stage is a minimal/distroless runtime, the agent layer's apt-get may fail — consider either editing the final stage to use a fuller base, or moving the agent layer to attach to a builder stage with apt-get available.`,
    );
  }

  // 5. BuildKit secrets — hard warning.
  if (/--mount=type=secret/i.test(base)) {
    warnings.push(
      'BuildKit secret mount (`--mount=type=secret`) detected. Sandcastle\'s image build does not run with BuildKit enabled, so any RUN that depends on a secret mount will fail. Either remove those RUNs from the agent\'s image (the agent does not need them — it only needs to be able to investigate code) or rewrite to use ARG/ENV.',
    );
  }

  // 6-7. Append agent layer + return.
  const content = `${base.trimEnd()}\n\n${AGENT_LAYER}`;
  return { content, detectedFrom, warnings };
}

// Parse `FROM <image> [AS <name>]` lines to identify stages. Used for
// the multi-stage warning. Doesn't try to be a real Dockerfile parser
// (comments, line continuations, etc. would need more work) — this is
// good enough for the warning's purpose.
type Stage = { image: string; name?: string };
function parseStages(content: string): Stage[] {
  const stages: Stage[] = [];
  const fromRegex = /^[\t ]*FROM[\t ]+(\S+)(?:[\t ]+AS[\t ]+(\S+))?/gim;
  let match: RegExpExecArray | null;
  while ((match = fromRegex.exec(content)) !== null) {
    stages.push({
      image: match[1]!,
      ...(match[2] ? { name: match[2] } : {}),
    });
  }
  return stages;
}
