import { execFile } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { mkdir as fsMkdir, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { promisify } from 'node:util';
import { run, type AgentStreamEvent } from '@ai-hero/sandcastle';
import type { Space } from '@jir/shared';
import { findInternalAccountById } from '../../agent-accounts/agent-accounts.service.js';
import { commit as gitCommit } from '../git/git.client.js';
import { AGENT_PROVIDERS } from '../agent-providers/registry.js';
import { localProcess } from './local-process.provider.js';

const execFileP = promisify(execFile);

export class AgentRunError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'AgentRunError';
  }
}

// Sandcastle's SessionPaths layer hardcodes the sandbox Claude projects
// dir at /home/agent/.claude/projects (see @ai-hero/sandcastle's
// SessionPaths.ts). For our localProcess provider host==sandbox, so we
// must point claude's HOME at that path or Sandcastle's session-capture
// step fails with ENOENT after the run.
//
// Cross-attempt isolation: session files inside this HOME are
// project-keyed by worktree path, so different attempts (different
// worktrees) get different session files. Shared HOME is safe.
const SHARED_AGENT_HOME = '/home/agent';

export type RunAgentArgs = {
  space: Space;
  attemptId: string;
  worktreePath: string;
  prompt: string;
  onEvent?: (event: AgentStreamEvent) => void;
};

// Temporary dev scaffold. Set MOCK_AGENT=1 to bypass the real Claude/Codex
// run and instead write a note file + make a single commit. Lets slices
// 9-15 exercise the orchestrator state machine (push → PR → Jira transition,
// live logs, retention, reopen context) without burning real LLM tokens.
//
// Remove (or gate behind appConfig.env === 'dev') once issue #24 lands —
// that's the slice that actually exercises prompt/HITL/quality work and
// needs real agent runs.
async function runMockAgent(args: RunAgentArgs): Promise<void> {
  // Branch name == issue key, and worktree path is `…/wt/<issueKey>` (see
  // branch.resolver). basename() is sufficient and avoids threading
  // issueKey through RunAgentArgs just for the mock.
  const issueKey = basename(args.worktreePath);

  type StreamScript = Array<{ delayMs: number; build: () => AgentStreamEvent }>;
  const script: StreamScript = [
    {
      delayMs: 200,
      build: () =>
        ({
          type: 'text',
          message: `Analyzing ${issueKey}. Reading the issue description and acceptance criteria.`,
          iteration: 1,
          timestamp: new Date(),
        }) as unknown as AgentStreamEvent,
    },
    {
      delayMs: 400,
      build: () =>
        ({
          type: 'toolCall',
          name: 'Read',
          formattedArgs: 'src/index.ts',
          iteration: 1,
          timestamp: new Date(),
        }) as unknown as AgentStreamEvent,
    },
    {
      delayMs: 500,
      build: () =>
        ({
          type: 'text',
          message: 'Found the relevant handler. Drafting a minimal fix.',
          iteration: 2,
          timestamp: new Date(),
        }) as unknown as AgentStreamEvent,
    },
    {
      delayMs: 500,
      build: () =>
        ({
          type: 'toolCall',
          name: 'Edit',
          formattedArgs: 'mock-agent-note.md',
          iteration: 2,
          timestamp: new Date(),
        }) as unknown as AgentStreamEvent,
    },
    {
      delayMs: 400,
      build: () =>
        ({
          type: 'text',
          message: 'Verifying against tests.',
          iteration: 3,
          timestamp: new Date(),
        }) as unknown as AgentStreamEvent,
    },
    {
      delayMs: 400,
      build: () =>
        ({
          type: 'toolCall',
          name: 'Bash',
          formattedArgs: 'npm test',
          iteration: 3,
          timestamp: new Date(),
        }) as unknown as AgentStreamEvent,
    },
    {
      delayMs: 300,
      build: () =>
        ({
          type: 'text',
          message: 'All tests pass. Implementation complete.',
          iteration: 4,
          timestamp: new Date(),
        }) as unknown as AgentStreamEvent,
    },
  ];

  for (const step of script) {
    await new Promise((resolve) => setTimeout(resolve, step.delayMs));
    args.onEvent?.(step.build());
  }

  // Always write to the same path so each attempt produces a real (small)
  // diff. The random UUID inside the body guarantees the diff is non-empty
  // even when re-running for the same issue.
  const notePath = join(args.worktreePath, 'mock-agent-note.md');
  const content = [
    '# Mock agent run',
    '',
    `- attempt: ${args.attemptId}`,
    `- issue: ${issueKey}`,
    `- timestamp: ${new Date().toISOString()}`,
    `- nonce: ${randomUUID()}`,
    '',
    'Generated by the MOCK_AGENT=1 scaffold. Unset MOCK_AGENT to run the real agent.',
    '',
  ].join('\n');
  await writeFile(notePath, content);
  await execFileP('git', ['-C', args.worktreePath, 'add', 'mock-agent-note.md']);

  // commit() in git.client uses --allow-empty-message + stdin so newlines
  // come through cleanly. The finalizer reads this subject/body via
  // headSubjectBody and squashes downstream, so the PR body formatter
  // ends up with this narrative.
  const subject = `Mock fix for ${issueKey}`;
  const body = [
    'MOCK_AGENT=1 — scaffolded commit to exercise the orchestrator end-to-end',
    'without invoking a real LLM. Replace with a real run by unsetting',
    'MOCK_AGENT.',
  ].join('\n');
  await gitCommit(args.worktreePath, `${subject}\n\n${body}`);
}

// Runs the Sandcastle agent inside the prepared worktree. Returns when the
// agent finishes (or errors). The caller (orchestrator) is responsible for
// looking at the resulting commits via git.revList and squashing.
export async function runAgent(args: RunAgentArgs): Promise<void> {
  if (process.env.MOCK_AGENT === '1') {
    return runMockAgent(args);
  }
  if (!args.space.agentAccountId) {
    throw new AgentRunError(
      'Space has no agent account assigned. Assign one in the Space detail page first.',
    );
  }
  const account = await findInternalAccountById(args.space.agentAccountId);
  if (!account) {
    throw new AgentRunError(
      `Agent account ${args.space.agentAccountId} not found (was it deleted?).`,
    );
  }
  const config = AGENT_PROVIDERS[account.provider];
  if (!config?.enabled || !config.sandcastleFactory) {
    throw new AgentRunError(
      `Provider "${account.provider}" is not enabled or has no Sandcastle factory wired.`,
    );
  }
  if (!config.models.includes(args.space.agentModel)) {
    throw new AgentRunError(
      `Model "${args.space.agentModel}" is not valid for ${config.label}.`,
    );
  }

  const home = SHARED_AGENT_HOME;
  await fsMkdir(home, { recursive: true });
  await fsMkdir(join(home, '.config'), { recursive: true });

  try {
    await run({
      agent: config.sandcastleFactory(args.space.agentModel),
      sandbox: localProcess({
        env: {
          [config.envVar]: account.apiKey,
          HOME: home,
        },
      }),
      cwd: args.worktreePath,
      prompt: args.prompt,
      // Slice 5's invariant: we own the worktree + branch, agent commits land
      // on whatever HEAD points at. branchStrategy: 'head' tells Sandcastle
      // not to manage branches itself.
      branchStrategy: { type: 'head' },
      // Sandcastle's file logger captures full output to disk under the
      // per-attempt HOME. Slice 7 will replace this with the real NDJSON
      // writer; for now the onAgentStreamEvent callback is a noop or the
      // caller's hook.
      logging: {
        type: 'file',
        path: join(home, 'sandcastle.log'),
        onAgentStreamEvent: args.onEvent ?? (() => {}),
      },
    });
  } catch (err) {
    throw new AgentRunError(
      err instanceof Error ? err.message : String(err),
    );
  }
}
